### ISSUE TITLE
pandora SCE track instance in ICARUS reco fcl files not properly specified

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/icaruscode#107]
Needs path release for 2020A production.

Please continue discussion here.

**Comment by brucehoward-physics** [comment]
Thanks for setting this up, Wes.

The issue is with the SCE tracks pointing back to the non-SCE pandora. From looking at a config_dumper output for example:

pandoraTrackGausSCECryo0: {
   PFParticleLabel: "pandoraGausCryo0"
   module_type: "LArPandoraTrackCreation"
}

Looking at the `reco_icarus.fcl` I think therefore the fix is just doing this:

`-icarus_reco_producers.pandoraTrackGausSCECryo0.PFParticleLabel:                                "pandoraGausCryo0"`
`+icarus_reco_producers.pandoraTrackGausSCECryo0.PFParticleLabel:                                "pandoraGausSCECryo0"`

and similarly for the `Cryo1` instance would fix this issue?

A testing plan could be as follows:
* I make a test release with the above fix and run reco1 again on a detsim file
* On the reco2 file from production corresponding to the same detsim file, run Christian's fhicl file
* @gMoreno05 can then look at the output of these and make sure the trees fill for the SCE products (showers and tracks) in both cases and that they look the same
* @mendezdpatricia can try to make a CAF file from these and ensure things look reasonable?

**Comment by wesketchum** [comment]
Hi @brucehoward-physics , @cfarnese , @gMoreno05 , and @mendezdpatricia:

what's the status here?

**Comment by brucehoward-physics** [comment]
There is a feature branch `feature/howard_sce_bugfix` with a few changed reco_icarus.fcl lines to point the SCE tracks to the SCE Pandora instance. This also has a fcl from @cfarnese that is meant to put in the corrected SCE products.

We took a nu+cosmic file and I re-ran the reco stage on 5 events and also Christian's fcl on 5 events from the production reco2 file of the same thing. (The files were large-ish and the processing not super fast).

@gMoreno05 checked that she was able to fill the trees with an analyzer module in both and checked that a few trees were the same between both. @mendezdpatricia checked that the output of running Christian's fcl was able to produce a CAF using the SCE products.

Folks should feel free to add more if there is more to add.

Not sure how it's felt best to proceed from the production side or @cfarnese . From our side, maybe we can/should look at non-SCE products for now or something to continue looking at the files.

**Comment by SFBayLaser** [comment]
Hi Bruce,
  If you are happy enough, can you generate a PR and I can do patch?
  Tracy

Sent from my iPhone X

On Nov 18, 2020, at 4:52 PM, Bruce Howard <notifications@github.com> wrote:

﻿

There is a feature branch feature/howard_sce_bugfix with a few changed reco_icarus.fcl lines to point the SCE tracks to the SCE Pandora instance. This also has a fcl from @cfarnese<https://github.com/cfarnese> that is meant to put in the corrected SCE products.

We took a nu+cosmic file and I re-ran the reco stage on 5 events and also Christian's fcl on 5 events from the production reco2 file of the same thing. (The files were large-ish and the processing not super fast).

@gMoreno05<https://github.com/gMoreno05> checked that she was able to fill the trees with an analyzer module in both and checked that a few trees were the same between both. @mendezdpatricia<https://github.com/mendezdpatricia> checked that the output of running Christian's fcl was able to produce a CAF using the SCE products.

Folks should feel free to add more if there is more to add.

Not sure how it's felt best to proceed from the production side or @cfarnese<https://github.com/cfarnese> . From our side, maybe we can/should look at non-SCE products for now or something to continue looking at the files.

**Comment by brucehoward-physics** [comment]
I mostly am, though I am curious about this one line that I noticed while looking at the code just now:

icarus_reco_producers.pandoraGausSCECryo0.PFPLabel:						                                 "pandoraGausCryo0"
icarus_reco_producers.pandoraGausSCECryo0.TrackLabel:						                               "pandoraTrackGausCryo0"


Is this the right setup? That `pandoraGausSCECryo0.TrackLabel` is `pandoraTrackGausCryo0` and not `pandoraTrackGausSCECryo0`? I guess this step runs before the pandoraTrackGausSCE step so maybe... If I @gputnam in an icaruscode issue will it push to him? 🤔

**Comment by cfarnese** [comment]
From my side, when you have clarified this last point, you can proceed and we can prepare the new release!

Christian

On Wed, 18 Nov 2020 17:23:38 -0800, Bruce Howard wrote

**Comment by gputnam** [comment]
@ Bruce I believe you are correct. The "SCE" chain of reconstruction should be using "SCE" producers all the way through.

My suggestion before merging this PR would be to re-process the reco2 SCE chain and make a CAF file (with SCE inputs) to make sure all the necessary modules are using the SCE-based input. That way you can be sure that all of these such errors have been corrected.

**Comment by brucehoward-physics** [comment]
The specific block that I am still questioning @gputnam is this one:

# Configure the SCE corrections
# For now: always assume t = 0
icarus_reco_producers.pandoraGausSCECryo0.T0Labels:                                            []
icarus_reco_producers.pandoraGausSCECryo0.T0LabelsCorrectT0:                                   []
icarus_reco_producers.pandoraGausSCECryo0.CorrectNoT0Tag:                                      true
icarus_reco_producers.pandoraGausSCECryo0.PFPLabel:                                                                              "pandoraGausCryo0"
icarus_reco_producers.pandoraGausSCECryo0.TrackLabel:                                                                          "pandoraTrackGausCryo0"

where there is the line

`icarus_reco_producers.pandoraGausSCECryo0.TrackLabel:                                                                          "pandoraTrackGausCryo0"`

The question is: Is this because of the way it's doing the corrections or is this also a typo?

As for making CAFs - I ran Christian's fcl over a few events from a nu+cosmic file and @mendezdpatricia tested that she could make a CAF with the file. I think she used the SCE products, but Diana can you please confirm?

**Comment by brucehoward-physics** [comment]
Today I learned that `#` causes a line to become giant in GitHub issue tracker... apologies.

**Comment by mendezdpatricia** [comment]
Yes, I used SCE products for the CAFs (as they are in cafmakerjob_icarus_sce.fcl)

**Comment by brucehoward-physics** [comment]
Cool that's what I thought. Gray can you comment on the above block of code then to (I think) finalize the discussion? I believe this block was added by you but if I'm wrong let me know :)

**Comment by gputnam** [comment]
Hi Bruce -- I think that line is a typo -- it should be "pandoraTrackGausSCECryo0" -- assuming that's how you guys are labeling the SCE-corrected tracks.

**Comment by brucehoward-physics** [comment]
Yeah the SCE tracks are under the label `pandoraTrackGausSCECryo0` as far as I can tell

It's interesting to me that the code still ran with that line as is but the other fix in place...

I will edit this line and try to remake a test file for @gMoreno05 and @mendezdpatricia to look at 🤔

**Comment by brucehoward-physics** [comment]
I thought a little more and talked to Ed, who said:

"The tracks are only used to look for T0s

As some of the T0 producers, e.g. CRTs, match to track objects

So I check each if each PFP has a T0, and if not if there is a track associated to the PFP that has a T0"

So I think it doesn't need the SCE Track listed...

I asked for confirmation but as it's late his time probably won't hear back before tomorrow. I've opened a PR in case @SFBayLaser  wants to pull in the PR tonight, unless we want to wait to hear.

**Comment by brucehoward-physics** [comment]
Okay Ed said "Yeah, that looks right to me" when I asked. E.g. that using non-SCE tracks in the `pandoraGausSCECryo0.TrackLabel` is OK I think.

So I believe the PR from last night is good to go.

**Comment by SFBayLaser** [comment]
I have merged in the PR to fix this and have installed a patch release - v09_09_02_01
I will leave this open for now in case this does not solve the problem, but plan to close it early next week.

**Comment by wesketchum** [comment]
Think this is now fixed and done. Closing.
