### ISSUE TITLE
PMT Decoder not safe for OM usage

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/icaruscode#133]
https://github.com/SBNSoftware/icaruscode/blob/d1f333d8e2ae382fd1051b379882b4fb844079a1/icaruscode/Decode/DaqDecoderICARUSPMT_module.cc#L84

reading fileinfo doesn't work for the online monitoring, as fileinfo is not filled for events that are delivered from the Dispatcher to the OM

Suggest an option in the decoder to not need to use this decoder tool? Ideally would have 'online' and 'offline' versions of this that could work if it's not hard to maintain.

**Comment by PetrilloAtWork** [comment]
The tool we are using should support `DecoderTool.ExtractConfiguration: false`, and that should be the default.
Is that not enough? or is it not working as expected?

**Comment by PetrilloAtWork** [comment]
The answer from @wesketchum is that setting that tool option is not enough since the error happens upstream of that.

**Comment by PetrilloAtWork** [comment]
Ok, ok, I entirely removed that feature. I hope you are happy now.

Indeed, I have removed from the decoder tool (and module) the extraction of the PMT configuration from the FHiCL metadata.
That feature was not utilised yet — it will be useful once we have PMT timestamps and trigger timestamps, since for example we need to know where in the waveform the trigger was, which is driven by the post-trigger fraction × buffer length.

There is a _art_ module, `PMTconfigurationExtraction`, which also extracts that configuration, and puts it into a run data product.
My idea is that when this information will be needed, it will be read from a data product instead of extracting it anew: it feels cleaner.
Both approaches required a change in the decoder tool interface: we are now back to the old one, ready to be changed again in the close future.
