### ISSUE TITLE
Finalize ICARUS flash-matching code

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/icaruscode#90]
Need to work with @drinkingkazu and team to incorporate any last configuration/testing for ICARUS flash-matching. Using this issue as a place-holder to discuss and coordinate what's needed.

**Comment by wesketchum** [comment]
Pull request ready/near ready: Tracy will update.

**Comment by wesketchum** [comment]
@SFBayLaser @drinkingkazu @ascarpel 

Believe initial version of this is done and in as part of our filtering? If so suggest we close this out.

**Comment by SFBayLaser** [comment]
I think the original intent was track-flash matching... so that is still outstanding (and was discussed in the last PMT recon meeting on Thursday, April 1 (no fooling!). However, it is also true that we have flash reconstruction working with the data now and if one interprets this issue a bit more narrowly then it could be defined as done...

**Comment by wesketchum** [comment]
I see, well I don't want to close out an ongoing thing then. It'd be good to know if this is a 'something about to be merged' thing, or if it's a 'todo' for the (hopefully near) future. If the latter, we should update the project to "Important Tasks: SBN Software Improvements " https://github.com/orgs/SBNSoftware/projects/12.

**Comment by wesketchum** [comment]
@SFBayLaser I'm closing this, in favor of making a new one that's more relevant.

**Comment by drinkingkazu** [comment]
Incorporation of the "lastes flash matching code into sbncode" is being worked out. probably more relevant to have an issue tracker there? We made so that OpT0Finder package can be literally git cloned inside sbncode and be part of the build while retaining its stand-alone build capability (i.e. literally you can "copy" the whole directory under sbncode and it can be `mrb`-ed). It might be sensible to use git module and unify the source code location as well (this allows OpT0Finder to remain its own repository).
