### ISSUE TITLE
avoid use of filter_genie_active.fcl

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/icaruscode#93]
I think we should modify generation fcls to avoid usage of the filter_genie_active.fcl: instead, just set volume in which to generate neutrinos to be the TPC active volume.

(I'm sure it's more complicated than this. But just noting an alternate solution would be good.)

@cfarnese can maybe comment?

**Comment by jzennamo** [comment]
I had thought that this was due to the "two cryostat" issue in the geometry meaning that there wasn't a convenient "sub volume" definition, maybe we can check with Robert Hatcher if we can provide a list of volumes instead of a single volume?

**Comment by cfarnese** [comment]
The idea to use filter_genie_active is related to the fact that in the icarus geometry if I call volTPCActive I have only 1 TPC (so 1/4 of the detector)... or at least it was in this way before the introduction of the split-wire geometry... My worry is that if we use the volTPCActive we risk to have neutrinos only in one region of the detector, introducing possible bias in the selection (for example in the physical TPC left and right the coll/ind2 wires have different inclination so if we consider only one TPC we consider only a possible inclination case)...   From my side we can even remove the filter stage and go to volTPCActive but maybe an additional check to verify at which volume the volTPCActive correspond in the split wire geometry is required (to be sure we are not selecting in this way only one logical TPC, that means 1/4 of one cryostat). Also the idea to provide a list of volumes is interesting (but due to my nexperience I have never succeeded to do this, sorry!)

**Comment by PetrilloAtWork** [comment]
I think the essence of the problem was well captured by @jzennamo.
Previous interactions with Robert Hatcher led to the conclusion that `GENIEhelper` (and the GENIE geometry driver we use, if I recall correctly) do not support multiple volumes.
Unless the volume definition can be moved into GENIE, there is little difference in resource usage in having it in `filter_genie_active.fcl` (soon, `filter_genie_active_icarus.fcl`) or elsewhere. If it is matter of convenience, a configuration can be written to run the filter at `Gen` stage instead than using a separate one. The number of events written on output will still be lower than the requested ones.

**Comment by wesketchum** [comment]
Closing this ... if we need workflows for dealing with filtering then (to ensure more stable numbers of events per run), we may reopen a similar issue.
